Repository UCL-CCS/Nbed, pull requests merged in 2023-11, with the labels that each got.

#113 Savefile
  .gitignore
  CHANGELOG.md
  nbed/driver.py
  nbed/embed.py
  tests/test_builder.py
  tests/test_driver.py
  tests/test_embed.py
Labels: bug

#116 Specify frozen core
  CHANGELOG.md
  docs/notebooks/2. Orbital Localization Functions.ipynb
  nbed/ham_builder.py
  tests/test_builder.py
Labels: enhancement

#111 Virtual orbitals - SPADE
  CHANGELOG.md
  docs/notebooks/2. Orbital Localization Functions.ipynb
  nbed/driver.py
  nbed/embed.py
  nbed/ham_builder.py
  nbed/localizers/base.py
  nbed/localizers/pyscf.py
  nbed/localizers/spade.py
  poetry.lock
  pyproject.toml
  tests/test_driver.py
  tests/test_embed.py
  tests/test_localizers.py
Labels: enhancement

#114 add symmer functionality
  CHANGELOG.md
  nbed/ham_builder.py
  nbed/ham_converter.py
  nbed/localizers/base.py
  nbed/localizers/spade.py
  tests/test_builder.py
  tests/test_ham_converter.py
Labels: enhancement

#120 bump version to 0.0.2
  .github/workflows/release.yaml
  CHANGELOG.md
  CITATION.cff
  docs/source/conf.py
  pyproject.toml
Labels: release
